version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo/element
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: init
          command: |
            git submodule sync
            git submodule update --init

      - run:
          name: update submodule
          command: |
            cd ../
            git config --global user.email "${GITHUB_EMAIL}"
            git config --global user.name "Vue Regression Bot"

            git submodule update --remote vue
            git commit -am 'update vue'
            git push

      - run:
          name: build
          command: |
            cd ../vue
            yarn install
            yarn build
      
      - run: git checkout v2.4.4

      - restore_cache:
          keys:
          - yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ checksum "../vue/dist/vue.js" }}

      - run:
          name: link
          command:
            cd ../vue
            yarn link
            cd -
            yarn link vue

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ checksum "../vue/dist/vue.js" }}

      - run: yarn test
