version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: init
          command: |
            git submodule sync
            git submodule update --init
            cd vue
            yarn install --frozen-lockfile
            yarn build
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
            - ~/.cache/yarn

  # TODO: add nuxt.js@1.4.1, vuetify
  element:
    docker:
      - image: circleci/node:8-browsers

    working_directory: ~/repo/element

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: link
          command:
            cd ../vue
            yarn link
            cd -
            yarn link vue
      - run: git checkout v2.4.4

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "../vue/dist/vue.js" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "../vue/dist/vue.js" }}

      - run: yarn test

workflows:
  version: 2
  test_all:
    jobs:
      - checkout_code
      - element:
          requires:
            - checkout_code
