version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo/element
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: init
          command: |
            git submodule sync
            git submodule update --init
            cd ../vue
            yarn install
            yarn build
      - run:
          name: link
          command:
            cd ../vue
            yarn link
            cd -
            yarn link vue

      # TODO: cache
      
      - run: git checkout v2.4.4

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "../vue/dist/vue.js" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "../vue/dist/vue.js" }}

      - run: yarn test
