version: 2

defaults: &defaults
  docker:
      - image: circleci/node:8-browsers

jobs:
  update:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: init
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: update submodule
          command: |
            git config --global user.email "${GITHUB_EMAIL}"
            git config --global user.name "Vue Regression Bot"

            git submodule update --remote vue
            # if not triggered manually by vue update, git push will exit with code 1
            git commit -am 'update vue from circleci' || test 1 = 1
            git push || test 1 = 1

  build_vue:
    <<: *defaults
    working_directory: ~/repo/vue
    steps:
      - checkout:
          path: ~/repo

      - run:
          name: init
          command: |
            git submodule sync
            git submodule update --init

      - restore_cache:
          keys:
          - yarn-packages-v1-{{ checksum "yarn.lock" }}

      - run:
          name: install dependencies
          command: yarn install --pure-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}

      - run:
          name: build
          command: yarn build
      
      - run: |
          mkdir -p ~/workspace
          cp -R ~/repo/ ~/workspace/repo

      - persist_to_workspace:
          root: ~/workspace
          paths:
            - repo
    
  element:
    <<: *defaults
    working_directory: ~/workspace/repo/element
    steps:
      - attach_workspace:
          at: ~/workspace

      - run: git checkout v2.4.5
      - run:
          name: link packages
          command: |
            cd ../vue
            yarn link
            cd ./packages/vue-template-compiler/
            yarn link
            cd ~/workspace/repo/element/
            yarn link vue
            yarn link vue-template-compiler

      - restore_cache:
          keys:
          - yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ checksum "../vue/dist/vue.js" }}

      - run: yarn install

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ checksum "../vue/dist/vue.js" }}

      - run: yarn test

workflows:
  version: 2

  test_all:
    jobs:
      - build_vue
      - element:
          requires:
            - build_vue