version: 2
jobs:
  test_nuxt:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo/nuxt.js

    steps:
      - checkout
          path: ~/repo
      - run: git submodule sync
      - run: git submodule update --init
      - run: yarn install
      - run: yarn test